In [3]:
!echo "https://noteable.edina.ac.uk/user/$(jupyter notebook list | grep -oP '(?<=user\/).*(?=\/\?)' )/tree?token=$( jupyter notebook list | grep -oP '(?<=token=).*(?= ::)' )"

https://noteable.edina.ac.uk/user/sydovg2nqqfsazpsnqw6bm/tree?token=_55fBf7PSMKtV-qcrrUNig

In [4]:
# import cell
import os
import numpy as np
import pandas as pd
from datetime import datetime
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
# load dataset into dataframe
spotify_data = pd.read_csv('https://www.inf.ed.ac.uk/teaching/courses/fds/data/project-2021-2022/spotify/data.csv.zip')
spotify_data

,Position,Track Name,Artist,Streams,URL,Date,Region
0,1,Reggaetón Lento (Bailemos),CNCO,19272,https://open.spotify.com/track/3AEZUABDXNtecAO...,2017-01-01,ec
1,2,Chantaje,Shakira,19270,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,2017-01-01,ec
2,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,https://open.spotify.com/track/3QwBODjSEzelZyV...,2017-01-01,ec
3,4,Vente Pa' Ca,Ricky Martin,14954,https://open.spotify.com/track/7DM4BPaS7uofFul...,2017-01-01,ec
4,5,Safari,J Balvin,14269,https://open.spotify.com/track/6rQSrBHf7HlZjtc...,2017-01-01,ec
...,...,...,...,...,...,...,...
3441192,196,More Than You Know,Axwell /\ Ingrosso,2126,https://open.spotify.com/track/71bBFbfn2OBK5Qw...,2018-01-09,hk
3441193,197,Issues,Julia Michaels,2117,https://open.spotify.com/track/7vu0JkJh0ldukEY...,2018-01-09,hk
3441194,198,Tuo Fei Lun,Eason Chan,2112,https://open.spotify.com/track/0pmGleExiQyd0Hx...,2018-01-09,hk
3441195,199,面具,Alfred Hui,2102,https://open.spotify.com/track/58SUsgamkW6vFFq...,2018-01-09,hk
3441196,200,Let Her Go,Passenger,2088,https://open.spotify.com/track/2jyjhRf6DVbMPU5...,2018-01-09,hk

In [6]:
# -------- initial data exploration --------
column_names = spotify_data.columns
column_names

Index(['Position', 'Track Name', 'Artist', 'Streams', 'URL', 'Date', 'Region'], dtype='object')

In [7]:
# a dictionary of initial unique values in each column (column name: unique values)
columns_unique_dict = {}
for name in column_names:
    columns_unique_dict[name] = spotify_data[name].unique()
columns_unique_dict

{'Position': array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
        183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
        196, 197, 198, 199, 200]),
 'Track Name': array(['Reggaetón Lento (Bailemos)', 'Chantaje',
        'Otra Vez (feat. J Balvin)', ..., '有火', '繼續追', '無期'], dtype=object),
 'Artist': array(['CNCO', 'Shakira', 'Zion & Lennox', ..., 'E-Kids', 'Jane Zhang',
        '帶菌者'], dtype=object),
 'Streams': array([ 19272,  19270,  15761, ..., 109523,  99097,  87140]),
 'URL': array(['https://open.spotify.com/track/3AEZUABDXNtecAOSC1qTfo',
        'https://open.spotify.com/track/6mICuAdrwEjh6Y6lroV2Kg',
        'https://open.spotify.com/track/3QwBODjSEzelZyVjxPOHdq', ...,
        'https://open.spotify.com/track/484RuK3NdSwb8y6Z2cFpq4',
        'https://open.spotify.com/track/2yJXJzjCUHdGmWmlMNq0lt',
        'https://open.spotify.com/track/724MwpBKglgmnf2PIcvyAK'],
       dtype=object),
 'Date': array(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
        '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08',
        '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
        '2017-01-13', '2017-01-14', '2017-01-15', '2017-01-16',
        '2017-01-17', '2017-01-18', '2017-01-19', '2017-01-20',
        '2017-01-21', '2017-01-22', '2017-01-23', '2017-01-24',
        '2017-01-25', '2017-01-26', '2017-01-27', '2017-01-28',
        '2017-01-29', '2017-01-30', '2017-01-31', '2017-02-01',
        '2017-02-02', '2017-02-03', '2017-02-04', '2017-02-05',
        '2017-02-06', '2017-02-07', '2017-02-08', '2017-02-09',
        '2017-02-10', '2017-02-11', '2017-02-12', '2017-02-13',
        '2017-02-14', '2017-02-15', '2017-02-16', '2017-02-17',
        '2017-02-18', '2017-02-19', '2017-02-20', '2017-02-21',
        '2017-02-22', '2017-02-23', '2017-02-24', '2017-02-25',
        '2017-02-26', '2017-02-27', '2017-02-28', '2017-03-01',
        '2017-03-02', '2017-03-03', '2017-03-04', '2017-03-05',
        '2017-03-06', '2017-03-07', '2017-03-08', '2017-03-09',
        '2017-03-10', '2017-03-11', '2017-03-12', '2017-03-13',
        '2017-03-14', '2017-03-15', '2017-03-16', '2017-03-17',
        '2017-03-18', '2017-03-19', '2017-03-20', '2017-03-21',
        '2017-03-22', '2017-03-23', '2017-03-24', '2017-03-25',
        '2017-03-26', '2017-03-27', '2017-03-28', '2017-03-29',
        '2017-03-30', '2017-03-31', '2017-04-01', '2017-04-02',
        '2017-04-03', '2017-04-04', '2017-04-05', '2017-04-06',
        '2017-04-07', '2017-04-08', '2017-04-09', '2017-04-10',
        '2017-04-11', '2017-04-12', '2017-04-13', '2017-04-14',
        '2017-04-15', '2017-04-16', '2017-04-17', '2017-04-18',
        '2017-04-19', '2017-04-20', '2017-04-21', '2017-04-22',
        '2017-04-23', '2017-04-24', '2017-04-25', '2017-04-26',
        '2017-04-27', '2017-04-28', '2017-04-29', '2017-04-30',
        '2017-05-01', '2017-05-02', '2017-05-03', '2017-05-04',
        '2017-05-05', '2017-05-06', '2017-05-07', '2017-05-08',
        '2017-05-09', '2017-05-10', '2017-05-11', '2017-05-12',
        '2017-05-13', '2017-05-14', '2017-05-15', '2017-05-16',
        '2017-05-17', '2017-05-18', '2017-05-19', '2017-05-20',
        '2017-05-21', '2017-05-22', '2017-05-23', '2017-05-24',
        '2017-05-25', '2017-05-26', '2017-05-27', '2017-05-28',
        '2017-05-29', '2017-06-01', '2017-06-03', '2017-06-04',
        '2017-06-05', '2017-06-06', '2017-06-07', '2017-06-08',
        '2017-06-09', '2017-06-10', '2017-06-11', '2017-06-12',
        '2017-06-13', '2017-06-14', '2017-06-15', '2017-06-16',
        '2017-06-17', '2017-06-18', '2017-06-19', '2017-06-20',
        '2017-06-21', '2017-06-22', '2017-06-23', '2017-06-24',
        '2017-06-25', '2017-06-26', '2017-06-27', '2017-06-28',
        '2017-06-29', '2017-06-30', '2017-07-01', '2017-07-02',
        '2017-07-03', '2017-07-04', '2017-07-05', '2017-07-06',
        '2017-07-07', '2017-07-08', '2017-07-09', '2017-07-10',
        '2017-07-11', '2017-07-12', '2017-07-13', '2017-07-14',
        '2017-07-15', '2017-07-16', '2017-07-17', '2017-07-18',
        '2017-07-19', '2017-07-20', '2017-07-21', '2017-07-22',
        '2017-07-23', '2017-07-24', '2017-07-25', '2017-07-26',
        '2017-07-27', '2017-07-28', '2017-07-29', '2017-07-30',
        '2017-07-31', '2017-08-01', '2017-08-02', '2017-08-03',
        '2017-08-04', '2017-08-05', '2017-08-06', '2017-08-07',
        '2017-08-08', '2017-08-09', '2017-08-10', '2017-08-11',
        '2017-08-12', '2017-08-13', '2017-08-14', '2017-08-15',
        '2017-08-16', '2017-08-17', '2017-08-18', '2017-08-19',
        '2017-08-20', '2017-08-21', '2017-08-22', '2017-08-23',
        '2017-08-24', '2017-08-25', '2017-08-26', '2017-08-27',
        '2017-08-28', '2017-08-29', '2017-08-30', '2017-08-31',
        '2017-09-01', '2017-09-02', '2017-09-03', '2017-09-04',
        '2017-09-05', '2017-09-06', '2017-09-07', '2017-09-08',
        '2017-09-09', '2017-09-10', '2017-09-11', '2017-09-12',
        '2017-09-13', '2017-09-14', '2017-09-15', '2017-09-16',
        '2017-09-17', '2017-09-18', '2017-09-19', '2017-09-20',
        '2017-09-21', '2017-09-22', '2017-09-23', '2017-09-24',
        '2017-09-25', '2017-09-26', '2017-09-27', '2017-09-28',
        '2017-09-29', '2017-09-30', '2017-10-01', '2017-10-02',
        '2017-10-03', '2017-10-04', '2017-10-05', '2017-10-06',
        '2017-10-07', '2017-10-08', '2017-10-09', '2017-10-10',
        '2017-10-11', '2017-10-12', '2017-10-13', '2017-10-14',
        '2017-10-15', '2017-10-16', '2017-10-17', '2017-10-18',
        '2017-10-19', '2017-10-20', '2017-10-21', '2017-10-22',
        '2017-10-23', '2017-10-24', '2017-10-25', '2017-10-26',
        '2017-10-27', '2017-10-28', '2017-10-29', '2017-10-30',
        '2017-10-31', '2017-11-01', '2017-11-02', '2017-11-03',
        '2017-11-04', '2017-11-05', '2017-11-06', '2017-11-07',
        '2017-11-08', '2017-11-09', '2017-11-10', '2017-11-11',
        '2017-11-12', '2017-11-13', '2017-11-14', '2017-11-15',
        '2017-11-16', '2017-11-17', '2017-11-18', '2017-11-19',
        '2017-11-20', '2017-11-21', '2017-11-22', '2017-11-23',
        '2017-11-24', '2017-11-25', '2017-11-26', '2017-11-27',
        '2017-11-28', '2017-11-29', '2017-11-30', '2017-12-01',
        '2017-12-02', '2017-12-03', '2017-12-04', '2017-12-05',
        '2017-12-06', '2017-12-07', '2017-12-08', '2017-12-09',
        '2017-12-10', '2017-12-11', '2017-12-12', '2017-12-13',
        '2017-12-14', '2017-12-15', '2017-12-16', '2017-12-17',
        '2017-12-18', '2017-12-19', '2017-12-20', '2017-12-21',
        '2017-12-22', '2017-12-23', '2017-12-24', '2017-12-25',
        '2017-12-26', '2017-12-27', '2017-12-28', '2017-12-29',
        '2017-12-30', '2017-12-31', '2018-01-01', '2018-01-02',
        '2018-01-03', '2018-01-04', '2018-01-05', '2018-01-06',
        '2018-01-07', '2018-01-08', '2018-01-09'], dtype=object),
 'Region': array(['ec', 'fr', 'ar', 'fi', 'no', 'it', 'lt', 'ph', 'tw', 'nz', 'ee',
        'tr', 'us', 'sv', 'cr', 'de', 'cl', 'jp', 'br', 'hn', 'gt', 'ch',
        'hu', 'ca', 'pe', 'be', 'my', 'dk', 'bo', 'pl', 'at', 'pt', 'se',
        'mx', 'pa', 'uy', 'is', 'es', 'cz', 'ie', 'nl', 'sk', 'co', 'sg',
        'id', 'do', 'lu', 'gb', 'global', 'py', 'au', 'lv', 'gr', 'hk'],
       dtype=object)}

In [8]:
# transform the region codes to all caps
spotify_data["Region"] = spotify_data["Region"].transform(lambda code: code.upper())

In [9]:
# -------- data cleaning & processing --------
# remove the URL column - no use for it, excessive data
cleaned_spotify_data = spotify_data.copy()

# since we have a question to investigate which day of the week and month there are more streams, we add "Day Of Week" and "Day Of Month"
cleaned_spotify_data["Day Of Month"] = cleaned_spotify_data["Date"].transform(lambda date: int(date[-2:]))
cleaned_spotify_data["Day Of Week"] = cleaned_spotify_data["Date"].transform(lambda date: datetime.strptime(date,'%Y-%m-%d').weekday())

In [10]:
# check for NaN values
for column in cleaned_spotify_data.columns:  # print out number of NaN values in each column: identify where the NaNs are
    print(column, cleaned_spotify_data[column].isnull().sum())

# drop na values in track names, as we definitely cannot predict those from the other values
cleaned_spotify_data = cleaned_spotify_data.dropna(axis=0, subset=["Artist"])

# print out number of NaN values in each column again
for column in cleaned_spotify_data.columns:
    print(column, cleaned_spotify_data[column].isnull().sum())
# Note: result is 0 - no more NaNs left!
# Cleaned 67 rows

# delete the "URL" column from our DataFrame
cleaned_spotify_data = cleaned_spotify_data.drop(columns="URL")

Position 0
Track Name 657
Artist 657
Streams 0
URL 8
Date 0
Region 0
Day Of Month 0
Day Of Week 0
Position 0
Track Name 0
Artist 0
Streams 0
URL 0
Date 0
Region 0
Day Of Month 0
Day Of Week 0

In [11]:
cleaned_spotify_data

,Position,Track Name,Artist,Streams,Date,Region,Day Of Month,Day Of Week
0,1,Reggaetón Lento (Bailemos),CNCO,19272,2017-01-01,EC,1,6
1,2,Chantaje,Shakira,19270,2017-01-01,EC,1,6
2,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,2017-01-01,EC,1,6
3,4,Vente Pa' Ca,Ricky Martin,14954,2017-01-01,EC,1,6
4,5,Safari,J Balvin,14269,2017-01-01,EC,1,6
...,...,...,...,...,...,...,...,...
3441192,196,More Than You Know,Axwell /\ Ingrosso,2126,2018-01-09,HK,9,1
3441193,197,Issues,Julia Michaels,2117,2018-01-09,HK,9,1
3441194,198,Tuo Fei Lun,Eason Chan,2112,2018-01-09,HK,9,1
3441195,199,面具,Alfred Hui,2102,2018-01-09,HK,9,1
3441196,200,Let Her Go,Passenger,2088,2018-01-09,HK,9,1

In [12]:
regionCode_data = pd.read_csv("regioncodes_to_names.csv")
regionCode_data = regionCode_data[["name","alpha-2"]].copy()
regionCode_data

                  name alpha-2
0          Afghanistan      AF
1        Åland Islands      AX
2              Albania      AL
3              Algeria      DZ
4       American Samoa      AS
..                 ...     ...
244  Wallis and Futuna      WF
245     Western Sahara      EH
246              Yemen      YE
247             Zambia      ZM
248           Zimbabwe      ZW

[249 rows x 2 columns]

In [13]:
regionName_dict = dict(zip(regionCode_data['alpha-2'], regionCode_data['name']))
regionName_dict['GLOBAL'] = 'Global'
regionName_dict["GB"] = "United Kingdom"
regionName_dict

{'AF': 'Afghanistan',
 'AX': 'Åland Islands',
 'AL': 'Albania',
 'DZ': 'Algeria',
 'AS': 'American Samoa',
 'AD': 'Andorra',
 'AO': 'Angola',
 'AI': 'Anguilla',
 'AQ': 'Antarctica',
 'AG': 'Antigua and Barbuda',
 'AR': 'Argentina',
 'AM': 'Armenia',
 'AW': 'Aruba',
 'AU': 'Australia',
 'AT': 'Austria',
 'AZ': 'Azerbaijan',
 'BS': 'Bahamas',
 'BH': 'Bahrain',
 'BD': 'Bangladesh',
 'BB': 'Barbados',
 'BY': 'Belarus',
 'BE': 'Belgium',
 'BZ': 'Belize',
 'BJ': 'Benin',
 'BM': 'Bermuda',
 'BT': 'Bhutan',
 'BO': 'Bolivia (Plurinational State of)',
 'BQ': 'Bonaire, Sint Eustatius and Saba',
 'BA': 'Bosnia and Herzegovina',
 'BW': 'Botswana',
 'BV': 'Bouvet Island',
 'BR': 'Brazil',
 'IO': 'British Indian Ocean Territory',
 'BN': 'Brunei Darussalam',
 'BG': 'Bulgaria',
 'BF': 'Burkina Faso',
 'BI': 'Burundi',
 'CV': 'Cabo Verde',
 'KH': 'Cambodia',
 'CM': 'Cameroon',
 'CA': 'Canada',
 'KY': 'Cayman Islands',
 'CF': 'Central African Republic',
 'TD': 'Chad',
 'CL': 'Chile',
 'CN': 'China',
 'CX': 'Christmas Island',
 'CC': 'Cocos (Keeling) Islands',
 'CO': 'Colombia',
 'KM': 'Comoros',
 'CG': 'Congo',
 'CD': 'Congo, Democratic Republic of the',
 'CK': 'Cook Islands',
 'CR': 'Costa Rica',
 'CI': "Côte d'Ivoire",
 'HR': 'Croatia',
 'CU': 'Cuba',
 'CW': 'Curaçao',
 'CY': 'Cyprus',
 'CZ': 'Czechia',
 'DK': 'Denmark',
 'DJ': 'Djibouti',
 'DM': 'Dominica',
 'DO': 'Dominican Republic',
 'EC': 'Ecuador',
 'EG': 'Egypt',
 'SV': 'El Salvador',
 'GQ': 'Equatorial Guinea',
 'ER': 'Eritrea',
 'EE': 'Estonia',
 'SZ': 'Eswatini',
 'ET': 'Ethiopia',
 'FK': 'Falkland Islands (Malvinas)',
 'FO': 'Faroe Islands',
 'FJ': 'Fiji',
 'FI': 'Finland',
 'FR': 'France',
 'GF': 'French Guiana',
 'PF': 'French Polynesia',
 'TF': 'French Southern Territories',
 'GA': 'Gabon',
 'GM': 'Gambia',
 'GE': 'Georgia',
 'DE': 'Germany',
 'GH': 'Ghana',
 'GI': 'Gibraltar',
 'GR': 'Greece',
 'GL': 'Greenland',
 'GD': 'Grenada',
 'GP': 'Guadeloupe',
 'GU': 'Guam',
 'GT': 'Guatemala',
 'GG': 'Guernsey',
 'GN': 'Guinea',
 'GW': 'Guinea-Bissau',
 'GY': 'Guyana',
 'HT': 'Haiti',
 'HM': 'Heard Island and McDonald Islands',
 'VA': 'Holy See',
 'HN': 'Honduras',
 'HK': 'Hong Kong',
 'HU': 'Hungary',
 'IS': 'Iceland',
 'IN': 'India',
 'ID': 'Indonesia',
 'IR': 'Iran (Islamic Republic of)',
 'IQ': 'Iraq',
 'IE': 'Ireland',
 'IM': 'Isle of Man',
 'IL': 'Israel',
 'IT': 'Italy',
 'JM': 'Jamaica',
 'JP': 'Japan',
 'JE': 'Jersey',
 'JO': 'Jordan',
 'KZ': 'Kazakhstan',
 'KE': 'Kenya',
 'KI': 'Kiribati',
 'KP': "Korea (Democratic People's Republic of)",
 'KR': 'Korea, Republic of',
 'KW': 'Kuwait',
 'KG': 'Kyrgyzstan',
 'LA': "Lao People's Democratic Republic",
 'LV': 'Latvia',
 'LB': 'Lebanon',
 'LS': 'Lesotho',
 'LR': 'Liberia',
 'LY': 'Libya',
 'LI': 'Liechtenstein',
 'LT': 'Lithuania',
 'LU': 'Luxembourg',
 'MO': 'Macao',
 'MG': 'Madagascar',
 'MW': 'Malawi',
 'MY': 'Malaysia',
 'MV': 'Maldives',
 'ML': 'Mali',
 'MT': 'Malta',
 'MH': 'Marshall Islands',
 'MQ': 'Martinique',
 'MR': 'Mauritania',
 'MU': 'Mauritius',
 'YT': 'Mayotte',
 'MX': 'Mexico',
 'FM': 'Micronesia (Federated States of)',
 'MD': 'Moldova, Republic of',
 'MC': 'Monaco',
 'MN': 'Mongolia',
 'ME': 'Montenegro',
 'MS': 'Montserrat',
 'MA': 'Morocco',
 'MZ': 'Mozambique',
 'MM': 'Myanmar',
 nan: 'Namibia',
 'NR': 'Nauru',
 'NP': 'Nepal',
 'NL': 'Netherlands',
 'NC': 'New Caledonia',
 'NZ': 'New Zealand',
 'NI': 'Nicaragua',
 'NE': 'Niger',
 'NG': 'Nigeria',
 'NU': 'Niue',
 'NF': 'Norfolk Island',
 'MK': 'North Macedonia',
 'MP': 'Northern Mariana Islands',
 'NO': 'Norway',
 'OM': 'Oman',
 'PK': 'Pakistan',
 'PW': 'Palau',
 'PS': 'Palestine, State of',
 'PA': 'Panama',
 'PG': 'Papua New Guinea',
 'PY': 'Paraguay',
 'PE': 'Peru',
 'PH': 'Philippines',
 'PN': 'Pitcairn',
 'PL': 'Poland',
 'PT': 'Portugal',
 'PR': 'Puerto Rico',
 'QA': 'Qatar',
 'RE': 'Réunion',
 'RO': 'Romania',
 'RU': 'Russian Federation',
 'RW': 'Rwanda',
 'BL': 'Saint Barthélemy',
 'SH': 'Saint Helena, Ascension and Tristan da Cunha',
 'KN': 'Saint Kitts and Nevis',
 'LC': 'Saint Lucia',
 'MF': 'Saint Martin (French part)',
 'PM': 'Saint Pierre and Miquelon',
 'VC': 'Saint Vincent and the Grenadines',
 'WS': 'Samoa',
 'SM': 'San Marino',
 'ST': 'Sao Tome and Principe',
 'SA': 'Saudi Arabia',
 'SN': 'Senegal',
 'RS': 'Serbia',
 'SC': 'Seychelles',
 'SL': 'Sierra Leone',
 'SG': 'Singapore',
 'SX': 'Sint Maarten (Dutch part)',
 'SK': 'Slovakia',
 'SI': 'Slovenia',
 'SB': 'Solomon Islands',
 'SO': 'Somalia',
 'ZA': 'South Africa',
 'GS': 'South Georgia and the South Sandwich Islands',
 'SS': 'South Sudan',
 'ES': 'Spain',
 'LK': 'Sri Lanka',
 'SD': 'Sudan',
 'SR': 'Suriname',
 'SJ': 'Svalbard and Jan Mayen',
 'SE': 'Sweden',
 'CH': 'Switzerland',
 'SY': 'Syrian Arab Republic',
 'TW': 'Taiwan, Province of China',
 'TJ': 'Tajikistan',
 'TZ': 'Tanzania, United Republic of',
 'TH': 'Thailand',
 'TL': 'Timor-Leste',
 'TG': 'Togo',
 'TK': 'Tokelau',
 'TO': 'Tonga',
 'TT': 'Trinidad and Tobago',
 'TN': 'Tunisia',
 'TR': 'Turkey',
 'TM': 'Turkmenistan',
 'TC': 'Turks and Caicos Islands',
 'TV': 'Tuvalu',
 'UG': 'Uganda',
 'UA': 'Ukraine',
 'AE': 'United Arab Emirates',
 'GB': 'United Kingdom',
 'US': 'United States of America',
 'UM': 'United States Minor Outlying Islands',
 'UY': 'Uruguay',
 'UZ': 'Uzbekistan',
 'VU': 'Vanuatu',
 'VE': 'Venezuela (Bolivarian Republic of)',
 'VN': 'Viet Nam',
 'VG': 'Virgin Islands (British)',
 'VI': 'Virgin Islands (U.S.)',
 'WF': 'Wallis and Futuna',
 'EH': 'Western Sahara',
 'YE': 'Yemen',
 'ZM': 'Zambia',
 'ZW': 'Zimbabwe',
 'GLOBAL': 'Global'}

In [14]:
cleaned_spotify_data["Region Name"] = cleaned_spotify_data["Region"].transform(lambda code: regionName_dict[code])

In [15]:
cleaned_spotify_data

,Position,Track Name,Artist,Streams,Date,Region,Day Of Month,Day Of Week,Region Name
0,1,Reggaetón Lento (Bailemos),CNCO,19272,2017-01-01,EC,1,6,Ecuador
1,2,Chantaje,Shakira,19270,2017-01-01,EC,1,6,Ecuador
2,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,2017-01-01,EC,1,6,Ecuador
3,4,Vente Pa' Ca,Ricky Martin,14954,2017-01-01,EC,1,6,Ecuador
4,5,Safari,J Balvin,14269,2017-01-01,EC,1,6,Ecuador
...,...,...,...,...,...,...,...,...,...
3441192,196,More Than You Know,Axwell /\ Ingrosso,2126,2018-01-09,HK,9,1,Hong Kong
3441193,197,Issues,Julia Michaels,2117,2018-01-09,HK,9,1,Hong Kong
3441194,198,Tuo Fei Lun,Eason Chan,2112,2018-01-09,HK,9,1,Hong Kong
3441195,199,面具,Alfred Hui,2102,2018-01-09,HK,9,1,Hong Kong
3441196,200,Let Her Go,Passenger,2088,2018-01-09,HK,9,1,Hong Kong

In [20]:
# add region names to our dictionary of unique column values
columns_unique_dict["Region Name"] = cleaned_spotify_data["Region Name"].unique()
columns_unique_dict["Region"] = cleaned_spotify_data["Region"].unique()
columns_unique_dict

{'Position': array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
        183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
        196, 197, 198, 199, 200]),
 'Track Name': array(['Reggaetón Lento (Bailemos)', 'Chantaje',
        'Otra Vez (feat. J Balvin)', ..., '有火', '繼續追', '無期'], dtype=object),
 'Artist': array(['CNCO', 'Shakira', 'Zion & Lennox', ..., 'E-Kids', 'Jane Zhang',
        '帶菌者'], dtype=object),
 'Streams': array([ 19272,  19270,  15761, ..., 109523,  99097,  87140]),
 'URL': array(['https://open.spotify.com/track/3AEZUABDXNtecAOSC1qTfo',
        'https://open.spotify.com/track/6mICuAdrwEjh6Y6lroV2Kg',
        'https://open.spotify.com/track/3QwBODjSEzelZyVjxPOHdq', ...,
        'https://open.spotify.com/track/484RuK3NdSwb8y6Z2cFpq4',
        'https://open.spotify.com/track/2yJXJzjCUHdGmWmlMNq0lt',
        'https://open.spotify.com/track/724MwpBKglgmnf2PIcvyAK'],
       dtype=object),
 'Date': array(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
        '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08',
        '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
        '2017-01-13', '2017-01-14', '2017-01-15', '2017-01-16',
        '2017-01-17', '2017-01-18', '2017-01-19', '2017-01-20',
        '2017-01-21', '2017-01-22', '2017-01-23', '2017-01-24',
        '2017-01-25', '2017-01-26', '2017-01-27', '2017-01-28',
        '2017-01-29', '2017-01-30', '2017-01-31', '2017-02-01',
        '2017-02-02', '2017-02-03', '2017-02-04', '2017-02-05',
        '2017-02-06', '2017-02-07', '2017-02-08', '2017-02-09',
        '2017-02-10', '2017-02-11', '2017-02-12', '2017-02-13',
        '2017-02-14', '2017-02-15', '2017-02-16', '2017-02-17',
        '2017-02-18', '2017-02-19', '2017-02-20', '2017-02-21',
        '2017-02-22', '2017-02-23', '2017-02-24', '2017-02-25',
        '2017-02-26', '2017-02-27', '2017-02-28', '2017-03-01',
        '2017-03-02', '2017-03-03', '2017-03-04', '2017-03-05',
        '2017-03-06', '2017-03-07', '2017-03-08', '2017-03-09',
        '2017-03-10', '2017-03-11', '2017-03-12', '2017-03-13',
        '2017-03-14', '2017-03-15', '2017-03-16', '2017-03-17',
        '2017-03-18', '2017-03-19', '2017-03-20', '2017-03-21',
        '2017-03-22', '2017-03-23', '2017-03-24', '2017-03-25',
        '2017-03-26', '2017-03-27', '2017-03-28', '2017-03-29',
        '2017-03-30', '2017-03-31', '2017-04-01', '2017-04-02',
        '2017-04-03', '2017-04-04', '2017-04-05', '2017-04-06',
        '2017-04-07', '2017-04-08', '2017-04-09', '2017-04-10',
        '2017-04-11', '2017-04-12', '2017-04-13', '2017-04-14',
        '2017-04-15', '2017-04-16', '2017-04-17', '2017-04-18',
        '2017-04-19', '2017-04-20', '2017-04-21', '2017-04-22',
        '2017-04-23', '2017-04-24', '2017-04-25', '2017-04-26',
        '2017-04-27', '2017-04-28', '2017-04-29', '2017-04-30',
        '2017-05-01', '2017-05-02', '2017-05-03', '2017-05-04',
        '2017-05-05', '2017-05-06', '2017-05-07', '2017-05-08',
        '2017-05-09', '2017-05-10', '2017-05-11', '2017-05-12',
        '2017-05-13', '2017-05-14', '2017-05-15', '2017-05-16',
        '2017-05-17', '2017-05-18', '2017-05-19', '2017-05-20',
        '2017-05-21', '2017-05-22', '2017-05-23', '2017-05-24',
        '2017-05-25', '2017-05-26', '2017-05-27', '2017-05-28',
        '2017-05-29', '2017-06-01', '2017-06-03', '2017-06-04',
        '2017-06-05', '2017-06-06', '2017-06-07', '2017-06-08',
        '2017-06-09', '2017-06-10', '2017-06-11', '2017-06-12',
        '2017-06-13', '2017-06-14', '2017-06-15', '2017-06-16',
        '2017-06-17', '2017-06-18', '2017-06-19', '2017-06-20',
        '2017-06-21', '2017-06-22', '2017-06-23', '2017-06-24',
        '2017-06-25', '2017-06-26', '2017-06-27', '2017-06-28',
        '2017-06-29', '2017-06-30', '2017-07-01', '2017-07-02',
        '2017-07-03', '2017-07-04', '2017-07-05', '2017-07-06',
        '2017-07-07', '2017-07-08', '2017-07-09', '2017-07-10',
        '2017-07-11', '2017-07-12', '2017-07-13', '2017-07-14',
        '2017-07-15', '2017-07-16', '2017-07-17', '2017-07-18',
        '2017-07-19', '2017-07-20', '2017-07-21', '2017-07-22',
        '2017-07-23', '2017-07-24', '2017-07-25', '2017-07-26',
        '2017-07-27', '2017-07-28', '2017-07-29', '2017-07-30',
        '2017-07-31', '2017-08-01', '2017-08-02', '2017-08-03',
        '2017-08-04', '2017-08-05', '2017-08-06', '2017-08-07',
        '2017-08-08', '2017-08-09', '2017-08-10', '2017-08-11',
        '2017-08-12', '2017-08-13', '2017-08-14', '2017-08-15',
        '2017-08-16', '2017-08-17', '2017-08-18', '2017-08-19',
        '2017-08-20', '2017-08-21', '2017-08-22', '2017-08-23',
        '2017-08-24', '2017-08-25', '2017-08-26', '2017-08-27',
        '2017-08-28', '2017-08-29', '2017-08-30', '2017-08-31',
        '2017-09-01', '2017-09-02', '2017-09-03', '2017-09-04',
        '2017-09-05', '2017-09-06', '2017-09-07', '2017-09-08',
        '2017-09-09', '2017-09-10', '2017-09-11', '2017-09-12',
        '2017-09-13', '2017-09-14', '2017-09-15', '2017-09-16',
        '2017-09-17', '2017-09-18', '2017-09-19', '2017-09-20',
        '2017-09-21', '2017-09-22', '2017-09-23', '2017-09-24',
        '2017-09-25', '2017-09-26', '2017-09-27', '2017-09-28',
        '2017-09-29', '2017-09-30', '2017-10-01', '2017-10-02',
        '2017-10-03', '2017-10-04', '2017-10-05', '2017-10-06',
        '2017-10-07', '2017-10-08', '2017-10-09', '2017-10-10',
        '2017-10-11', '2017-10-12', '2017-10-13', '2017-10-14',
        '2017-10-15', '2017-10-16', '2017-10-17', '2017-10-18',
        '2017-10-19', '2017-10-20', '2017-10-21', '2017-10-22',
        '2017-10-23', '2017-10-24', '2017-10-25', '2017-10-26',
        '2017-10-27', '2017-10-28', '2017-10-29', '2017-10-30',
        '2017-10-31', '2017-11-01', '2017-11-02', '2017-11-03',
        '2017-11-04', '2017-11-05', '2017-11-06', '2017-11-07',
        '2017-11-08', '2017-11-09', '2017-11-10', '2017-11-11',
        '2017-11-12', '2017-11-13', '2017-11-14', '2017-11-15',
        '2017-11-16', '2017-11-17', '2017-11-18', '2017-11-19',
        '2017-11-20', '2017-11-21', '2017-11-22', '2017-11-23',
        '2017-11-24', '2017-11-25', '2017-11-26', '2017-11-27',
        '2017-11-28', '2017-11-29', '2017-11-30', '2017-12-01',
        '2017-12-02', '2017-12-03', '2017-12-04', '2017-12-05',
        '2017-12-06', '2017-12-07', '2017-12-08', '2017-12-09',
        '2017-12-10', '2017-12-11', '2017-12-12', '2017-12-13',
        '2017-12-14', '2017-12-15', '2017-12-16', '2017-12-17',
        '2017-12-18', '2017-12-19', '2017-12-20', '2017-12-21',
        '2017-12-22', '2017-12-23', '2017-12-24', '2017-12-25',
        '2017-12-26', '2017-12-27', '2017-12-28', '2017-12-29',
        '2017-12-30', '2017-12-31', '2018-01-01', '2018-01-02',
        '2018-01-03', '2018-01-04', '2018-01-05', '2018-01-06',
        '2018-01-07', '2018-01-08', '2018-01-09'], dtype=object),
 'Region': array(['EC', 'FR', 'AR', 'FI', 'NO', 'IT', 'LT', 'PH', 'TW', 'NZ', 'EE',
        'TR', 'US', 'SV', 'CR', 'DE', 'CL', 'JP', 'BR', 'HN', 'GT', 'CH',
        'HU', 'CA', 'PE', 'BE', 'MY', 'DK', 'BO', 'PL', 'AT', 'PT', 'SE',
        'MX', 'PA', 'UY', 'IS', 'ES', 'CZ', 'IE', 'NL', 'SK', 'CO', 'SG',
        'ID', 'DO', 'LU', 'GB', 'GLOBAL', 'PY', 'AU', 'LV', 'GR', 'HK'],
       dtype=object),
 'Region Name': array(['Ecuador', 'France', 'Argentina', 'Finland', 'Norway', 'Italy',
        'Lithuania', 'Philippines', 'Taiwan, Province of China',
        'New Zealand', 'Estonia', 'Turkey', 'United States of America',
        'El Salvador', 'Costa Rica', 'Germany', 'Chile', 'Japan', 'Brazil',
        'Honduras', 'Guatemala', 'Switzerland', 'Hungary', 'Canada',
        'Peru', 'Belgium', 'Malaysia', 'Denmark',
        'Bolivia (Plurinational State of)', 'Poland', 'Austria',
        'Portugal', 'Sweden', 'Mexico', 'Panama', 'Uruguay', 'Iceland',
        'Spain', 'Czechia', 'Ireland', 'Netherlands', 'Slovakia',
        'Colombia', 'Singapore', 'Indonesia', 'Dominican Republic',
        'Luxembourg', 'United Kingdom', 'Global', 'Paraguay', 'Australia',
        'Latvia', 'Greece', 'Hong Kong'], dtype=object)}

In [21]:
# top ranking song in each region
ranking_df = cleaned_spotify_data[["Position", "Track Name", "Artist", "Region"]].copy()
ranking_df["Position Index"] = ranking_df["Position"].transform(lambda x: 201-x)
ranking_df = ranking_df.drop(columns="Position")
ranking_df

                         Track Name              Artist Region  Position Index
0        Reggaetón Lento (Bailemos)                CNCO     EC             200
1                          Chantaje             Shakira     EC             199
2         Otra Vez (feat. J Balvin)       Zion & Lennox     EC             198
3                      Vente Pa' Ca        Ricky Martin     EC             197
4                            Safari            J Balvin     EC             196
...                             ...                 ...    ...             ...
3441192          More Than You Know  Axwell /\ Ingrosso     HK               5
3441193                      Issues      Julia Michaels     HK               4
3441194                 Tuo Fei Lun          Eason Chan     HK               3
3441195                          面具          Alfred Hui     HK               2
3441196                  Let Her Go           Passenger     HK               1

[3440540 rows x 4 columns]

In [22]:
top40Songs_dict = dict()
top10Artists_dict = dict()
count = 1
for region in columns_unique_dict["Region"]:
    print(count)
    count += 1
    region_df = ranking_df[ranking_df["Region"] == region]
    region_trackname_list = region_df["Track Name"].unique()
    region_artist_list = region_df["Artist"].unique()
    trackCreditRanking_list = []
    artistCreditRanking_list = []
    # calculate the "credit" of each individual track in the dataset
    for trackname in region_trackname_list:
        track_region_df = region_df[region_df["Track Name"] == trackname]
        trackCreditRanking_list.append([track_region_df["Position Index"].sum(), trackname])
    trackCreditRanking_list.sort()
    trackCreditRanking_list.reverse()
    top40Songs_dict[region] = np.array(trackCreditRanking_list[:40])
    
    #calculate the "credit" of each individual artist in the dataset
    for artist in region_artist_list:
        artist_region_df = region_df[region_df["Artist"] == artist]
        artistCreditRanking_list.append([artist_region_df["Position Index"].sum(), artist])
    artistCreditRanking_list.sort()
    artistCreditRanking_list.reverse()
    top10Artists_dict[region] = np.array(artistCreditRanking_list[:10])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54

In [19]:
top40Songs_dict

{'ec': array([], dtype=float64),
 'fr': array([], dtype=float64),
 'ar': array([], dtype=float64),
 'fi': array([], dtype=float64),
 'no': array([], dtype=float64),
 'it': array([], dtype=float64),
 'lt': array([], dtype=float64),
 'ph': array([], dtype=float64),
 'tw': array([], dtype=float64),
 'nz': array([], dtype=float64),
 'ee': array([], dtype=float64),
 'tr': array([], dtype=float64),
 'us': array([], dtype=float64),
 'sv': array([], dtype=float64),
 'cr': array([], dtype=float64),
 'de': array([], dtype=float64),
 'cl': array([], dtype=float64),
 'jp': array([], dtype=float64),
 'br': array([], dtype=float64),
 'hn': array([], dtype=float64),
 'gt': array([], dtype=float64),
 'ch': array([], dtype=float64),
 'hu': array([], dtype=float64),
 'ca': array([], dtype=float64),
 'pe': array([], dtype=float64),
 'be': array([], dtype=float64),
 'my': array([], dtype=float64),
 'dk': array([], dtype=float64),
 'bo': array([], dtype=float64),
 'pl': array([], dtype=float64),
 'at': array([], dtype=float64),
 'pt': array([], dtype=float64),
 'se': array([], dtype=float64),
 'mx': array([], dtype=float64),
 'pa': array([], dtype=float64),
 'uy': array([], dtype=float64),
 'is': array([], dtype=float64),
 'es': array([], dtype=float64),
 'cz': array([], dtype=float64),
 'ie': array([], dtype=float64),
 'nl': array([], dtype=float64),
 'sk': array([], dtype=float64),
 'co': array([], dtype=float64),
 'sg': array([], dtype=float64),
 'id': array([], dtype=float64),
 'do': array([], dtype=float64),
 'lu': array([], dtype=float64),
 'gb': array([], dtype=float64),
 'global': array([], dtype=float64),
 'py': array([], dtype=float64),
 'au': array([], dtype=float64),
 'lv': array([], dtype=float64),
 'gr': array([], dtype=float64),
 'hk': array([], dtype=float64)}